PROJECT := prog
TARGET := prog
SOURCES := main.c

DEPS := libmy
deps_get_libmy := custom cp -rf libmy deps/src/; cp deps/src/libmy/Makefile.here deps/src/libmy/libmy.proj.mk
deps_ttype_libmya := libso

include .proj.mk/c-proj.mk
